### ISSUE TITLE
[IDEA] Per-device selection

### ISSUE THREAD

**Issue by MarcoRavich** [its-ashu-otf/Manage-Automatic-Driver-Updates#1]
Hi there,
I recently have issues with my Dell Optiplex 3000 integrated audio by Realtek: it refuses to play with vendor drivers but works with default (Microsoft) ones.
Solved - of course - by inhibiting the relative driver update, I found this interesting script @tenforums for easily do it: https://www.tenforums.com/tutorials/146562-prevent-windows-update-updating-specific-device-driver.html

It would be really useful to have a per-device (graphical) blocker, IMHO.

Hope that inspires.

**Comment by its-ashu-otf** [comment]
Can try to implement this but on a per device basis it would be hard. TBH in my usecases I never found automatic driver update to be helpful so made this script to disable them. Will try to add implemention like this. Thanks for the idea.

**Comment by MarcoRavich** [comment]
Well, AFAIK you can use [PNPDeviceID](https://www.pdq.com/powershell/get-pnpdevice/)...

...anyway DISM may help too:
https://www.guidingtech.com/how-to-check-hardware-devices-id-windows/
